### ISSUE TITLE
Not sending rpc when discovered by bootstrappers

### ISSUE THREAD

**Issue by hubertokf** [beingmohit/libp2p-rpc#5]
Hey,

I guess that when peer discover another by bootstrapper, it do not send rpc obj. How can i handle that?

**Comment by hubertokf** [comment]
digging on the code, I found this error: 

libp2p:rpc error during dialProtocol { Error: No available transports to dial peer QmbFhf9ebwKk8w3kv2WVMJ9yGAs5fsTnHzRXVzTqmLRF7p!
    at createError (/home/core/code/node_modules/err-code/index.js:4:44)
    at module.exports.CONNECTION_FAILED (/home/core/code/node_modules/libp2p-switch/src/errors.js:6:45)
    at nextTransport (/home/core/code/node_modules/libp2p-switch/src/connection/index.js:221:11)
    at switch.transport.dial (/home/core/code/node_modules/libp2p-switch/src/connection/index.js:234:18)
    at dialer.dialMany (/home/core/code/node_modules/libp2p-switch/src/transport.js:108:16)
    at f (/home/core/code/node_modules/once/once.js:25:25)
    at tryEach (/home/core/code/node_modules/libp2p-switch/src/limit-dialer/index.js:61:14)
    at /home/core/code/node_modules/libp2p-switch/node_modules/async/tryEach.js:78:9
    at /home/core/code/node_modules/libp2p-switch/node_modules/async/internal/once.js:12:16
    at replenish (/home/core/code/node_modules/libp2p-switch/node_modules/async/internal/eachOfLimit.js:61:25) code: 'CONNECTION_FAILED' } +47ms

**Comment by beingmohit** [comment]
Might be related to https://github.com/libp2p/js-libp2p-tcp/issues/95

Its supposed to be fixed in libp2p-tcp@v0.13.0

In package.json, it required v0.13.0

But in package-lock.json, its pulling v0.11

Can you confirm what version of libp2p-tcp you have installed?

@hubertokf

**Comment by beingmohit** [comment]
in yarn lock, its 0.12 xD

**Comment by hubertokf** [comment]
@beingmohit 

In one of my pulls, i fixed version to 0.13.0

core@core-VirtualBox:~/libp2p-rpc$ npm ls libp2p-tcp
libp2p-rpc@0.1.2 /home/core/libp2p-rpc
├─┬ libp2p-mdns@0.12.2
│ └── libp2p-tcp@0.13.0  deduped
└── libp2p-tcp@0.13.0
